import { existsSync, readFileSync, writeFileSync, chmodSync, unlinkSync } from "node:fs";
import { resolve, join } from "node:path";
import { resolveGitDir } from "./diff.js";
import { HOOK_NAME } from "./templates.js";

function getHooksDir(cwd: string): string {
  const gitDir = resolveGitDir(cwd);
  return resolve(gitDir, ".git", "hooks");
}

function getHookPath(cwd: string): string {
  return join(getHooksDir(cwd), HOOK_NAME);
}

function getBackupPath(cwd: string): string {
  return join(getHooksDir(cwd), `${HOOK_NAME}.commit-craft-backup`);
}

const HOOK_SCRIPT = `#!/bin/sh
# commit-craft prepare-commit-msg hook
# Auto-generated by commit-craft hook install
COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

# Only generate for normal commits (not merge, squash, etc.)
if [ -z "$COMMIT_SOURCE" ]; then
  GENERATED=$(commit-craft generate 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$GENERATED" ]; then
    # Prepend generated message, keeping any existing content
    EXISTING=""
    if [ -f "$COMMIT_MSG_FILE" ]; then
      EXISTING=$(cat "$COMMIT_MSG_FILE")
    fi
    printf '%s\\n\\n%s' "$GENERATED" "$EXISTING" > "$COMMIT_MSG_FILE"
  fi
fi
`;

export interface HookResult {
  success: boolean;
  message: string;
  path: string;
}

export function installHook(cwd: string): HookResult {
  const hooksDir = getHooksDir(cwd);

  if (!existsSync(hooksDir)) {
    return {
      success: false,
      message: `Hooks directory not found: ${hooksDir}. Is this a git repository?`,
      path: hooksDir,
    };
  }

  const hookPath = getHookPath(cwd);
  const backupPath = getBackupPath(cwd);

  if (existsSync(hookPath)) {
    const existing = readFileSync(hookPath, "utf-8");
    if (existing.includes("commit-craft")) {
      return {
        success: false,
        message: "commit-craft hook is already installed.",
        path: hookPath,
      };
    }

    writeFileSync(backupPath, existing, "utf-8");
  }

  writeFileSync(hookPath, HOOK_SCRIPT, "utf-8");
  chmodSync(hookPath, 0o755);

  return {
    success: true,
    message: `Hook installed at ${hookPath}` +
      (existsSync(backupPath) ? ` (backup created at ${backupPath})` : ""),
    path: hookPath,
  };
}

export function uninstallHook(cwd: string): HookResult {
  const hookPath = getHookPath(cwd);
  const backupPath = getBackupPath(cwd);

  if (!existsSync(hookPath)) {
    return {
      success: false,
      message: "No prepare-commit-msg hook found.",
      path: hookPath,
    };
  }

  const content = readFileSync(hookPath, "utf-8");
  if (!content.includes("commit-craft")) {
    return {
      success: false,
      message: "Existing hook was not installed by commit-craft. Not removing.",
      path: hookPath,
    };
  }

  unlinkSync(hookPath);

  if (existsSync(backupPath)) {
    writeFileSync(hookPath, readFileSync(backupPath, "utf-8"), "utf-8");
    if (existsSync(hookPath)) {
      chmodSync(hookPath, 0o755);
    }
    unlinkSync(backupPath);

    return {
      success: true,
      message: `Hook removed and backup restored at ${hookPath}.`,
      path: hookPath,
    };
  }

  return {
    success: true,
    message: `Hook removed from ${hookPath}.`,
    path: hookPath,
  };
}
